[package]
name = "rsc-parser"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rsc-parser"
path = "src/bin.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
memchr = "2.7.5"
